# Beispiel 3.7: Berechnung der Nicht-Schlüsselkomponenten
Bearbeitet von Franz Braun

Dieses Beispiel befindet sich im Lehrbuch auf den Seiten 27 - 28. Die Nummerierung
der verwendeten Gleichungen entspricht der Nummerierung im Lehrbuch. Das hier angewendete
Vorgehen entspricht dem im Lehrbuch vorgestellten Lösungsweg.

Zunächst werden die benötigten Pakete importiert.

In [25]:
### Import
import numpy as np
from scipy.optimize import root
from tabulate import tabulate

Aus dem Beispiel 3.6 ist die Matrix $N$ der stöchiometrischen Koeffizienten bekannt. Diese wird nun in die Teilmatrizen $N_{1,1}$ und $N_{2,1}$ unterteilt. In $N_{1,1}$ werden die Schlüsselkomponenten und in $N_{2,1}$ die Nicht-Schlüsselkomponenten betrachtet, so wie sie in den Schlüsselreaktionen vorkommen. 
Der Umsatz der Nicht-Schlüsselkomponenten kann mit der Gleichung 3.26 bestimmt werden. Hier wird das entsprechende Matrixprodukt als $MP$ definiert:

\begin{align*}
MP = N_{2,1} \, N_{1,1}^{-1}.
\end{align*}

Die inverse Matrix $N_{1,1}^{-1}$ wird zuvor in einem separaten Schritt aus $N_{1,1}$  gebildet.

In [26]:
                        # Reaktion j
N           = np.array([[  +3,  +1,  +2,  +1,  +1,   0], # H2
                        [  +1,  -1,   0,   0,  +1,  -2], # CO
                        [  -1,  -1,   0,   0,  -1,   0], # H2O
                        [  -1,   0,  -1,  -2,   0,   0], # CH4
                        [   0,   0,  +1,   0,  -1,  +1], # C
                        [   0,  +1,   0,   0,   0,  +1], # CO2
                        [   0,   0,   0,  +1,   0,   0]  # C2H6
                        ])          

                    
N_1_1       = np.array([[  +3,  +1,  +2,  +1],
                        [  +1,  -1,   0,   0],
                        [  -1,  -1,   0,   0],
                        [  -1,   0,  -1,  -2]
                        ])   

N_2_1       = np.array([[   0,   0,  +1,   0], 
                        [   0,  +1,   0,   0],
                        [   0,   0,   0,  +1] 
                        ]) 


N_1_1_inv   = np.linalg.inv(N_1_1)          # Bildung der inversen Matrix N_11^-1
print('N_11^-1 :', N_1_1_inv)


MP          = np.matmul(N_2_1, N_1_1_inv)   # Vektorprodukt
print('MP :', MP)

N_11^-1 : [[ 0.          0.5        -0.5         0.        ]
 [-0.         -0.5        -0.5        -0.        ]
 [ 0.66666667 -0.5         1.16666667  0.33333333]
 [-0.33333333 -0.         -0.33333333 -0.66666667]]
MP : [[ 0.66666667 -0.5         1.16666667  0.33333333]
 [ 0.         -0.5        -0.5         0.        ]
 [-0.33333333  0.         -0.33333333 -0.66666667]]


Im Folgenden wird $MP$ tabellarisch ausgeben. Jede Zeile entspricht der Stoffmengenänderung (bzw. Umsatz) einer Nicht-Schlüsselkomponente, während in den Spalten die Umsätze der Schlüsselkomponenten aufgeführt werden. Die Tabelle soll als Unterstützung der Umwandlung von der in Gleichung 3.26 gegebener Vektorschreibweise zu untenstehender Komponentenschreibweise dienen.

In [27]:
# Ausgabe der Ergebnisse als Tabelle

names_y  = np.array([['Delta_n_C / mol'], ['Delta_n_CO2 / mol'], ['Delta_n_C2H6 / mol']])


# Array für Tabelle
table = np.hstack((names_y, np.round(MP, 4)))

print(tabulate(table,headers = ['Delta_n_H2 / mol', 'Delta_n_CO / mol', 'Delta_n_H2O / mol', 'Delta_n_CH4 / mol']))

                      Delta_n_H2 / mol    Delta_n_CO / mol    Delta_n_H2O / mol    Delta_n_CH4 / mol
------------------  ------------------  ------------------  -------------------  -------------------
Delta_n_C / mol                 0.6667                -0.5               1.1667               0.3333
Delta_n_CO2 / mol               0                     -0.5              -0.5                  0
Delta_n_C2H6 / mol             -0.3333                 0                -0.3333              -0.6667


Aus der obigen Tabelle ergibt sich folgende Komponentenschreibweise zur Berechnung des Umsatzes von Nicht-Schlüsselkomponenten:

\begin{align*}
\Delta n_\mathrm{C} &= \frac{2}{3}\, \Delta n_\mathrm{H_2} - \frac{1}{2}\, \Delta n_\mathrm{CO} + \frac{7}{6}\, \Delta n_\mathrm{H_2O} + \frac{1}{3}\, \Delta n_\mathrm{CH_4},\\
\Delta n_\mathrm{CO_2} &= - \frac{1}{2}\, \Delta n_\mathrm{CO} - \frac{1}{2}\, \Delta n_\mathrm{H_2O},\\
\Delta n_\mathrm{C_2H_6} &= - \frac{1}{3}\, \Delta n_\mathrm{H_2} - \frac{1}{3}\, \Delta n_\mathrm{H_2O} - \frac{2}{3}\, \Delta n_\mathrm{CH_4}.
\end{align*}

Zahlenbeispiel: Wir nehmen an, dass folgende Umsätze für die Schlüsselkomponenten $\mathrm{H_2}$, $\mathrm{CO}$, $\mathrm{H_2O}$ und $\mathrm{CH_4}$ gemessen wurden: 

\begin{align*}
\Delta n_1 = \left[\begin{array}{c}30\\ 9\\ -10\\ -10\end{array}\right]\,\mathrm{mol}
\end{align*}

In [28]:
Delta_n_1 = np.array([[ 30,  # H2
                         9,  # CO
                       -10,  # H2O
                       -10]]) # CH4

Delta_n_2 = np.matmul(MP, Delta_n_1.T) # Vektorprodukt

print('Delta_n_2 :', Delta_n_2)

Delta_n_2 : [[ 5.0000000e-01]
 [ 5.0000000e-01]
 [-8.8817842e-16]]


Es ergeben sich für die Nicht-Schlüsselkomponenten nun folgende Umsätze:

\begin{align*}
\Delta n_2 = \left[\begin{array}{c}0,5\\ 0,5\\ 0\end{array}\right]\,\mathrm{mol}
\end{align*}

Es bildet sich also fester Kohlenstoff sowie $\mathrm{CO_2}$, was wahrscheinlich unerwünscht ist.